const Sequelize = require('sequelize');
module.exports = function(sequelize, DataTypes) {
  const Activity = sequelize.define('Activity', {
    id: {
      autoIncrement: true,
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      references: {
        model: 'users',
        key: 'id'
      }
    },
    activityType: {
      type: DataTypes.ENUM(
        'client', 'estimate', 'event', 'invoice', 'workOrder', 'purchaseOrder', 
        'user', 'role', 'permission', 'lineItem', 'payment', 'note', 'document',
        'communication', 'task', 'appointment', 'followUp', 'system',
        'payroll', 'payrollItem', 'payrollDeduction', 'userPayRate', 'userCheckIn', 'eventCheckin'
      ),
      allowNull: false,
      comment: 'Type of entity this activity relates to'
    },
    entityId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      comment: 'ID of the related entity (polymorphic relationship)'
    },
    action: {
      type: DataTypes.ENUM(
        'created', 'updated', 'deleted', 'viewed', 'approved', 'rejected', 
        'sent', 'received', 'completed', 'cancelled', 'scheduled', 'rescheduled',
        'assigned', 'unassigned', 'archived', 'restored', 'exported', 'imported',
        'loggedOn', 'loggedOut', 'statusChanged', 'paymentReceived', 'paymentSent',
        'fileUploaded', 'fileDeleted', 'emailSent', 'smsSent', 'callMade',
        'noteAdded', 'commentAdded', 'reminderSet', 'reminderTriggered'
      ),
      allowNull: false,
      comment: 'Action performed on the entity'
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: 'Human-readable description of the activity'
    },
    metadata: {
      type: DataTypes.JSON,
      allowNull: true,
      comment: 'Additional metadata for the activity (optional)'
    },
    companyId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      references: {
        model: 'companies',
        key: 'id',
      },
    },
    ipAddress: {
      type: DataTypes.STRING(45),
      allowNull: true,
      comment: 'IP address of the user who performed the action'
    },
    userAgent: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: 'User agent of the client that performed the action'
    },
    isSystemGenerated: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false,
      comment: 'Whether this activity was generated by the system automatically'
    },
    severity: {
      type: DataTypes.ENUM('low', 'medium', 'high', 'critical'),
      allowNull: false,
      defaultValue: 'low',
      comment: 'Severity level of the activity for filtering and notifications'
    },
    isVisible: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true,
      comment: 'Whether this activity should be visible in activity feeds'
    },
    tags: {
      type: DataTypes.JSON,
      allowNull: true,
      comment: 'Array of tags for categorization and filtering'
    },
    createdAt: {
      allowNull: false,
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP')
    },
    updatedAt: {
      allowNull: false,
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP')
    }
  }, {
    sequelize,
    tableName: 'activities',
    timestamps: true,
    indexes: [
      {
        name: "PRIMARY",
        unique: true,
        using: "BTREE",
        fields: [
          { name: "id" },
        ]
      },
      {
        name: "idx_activities_user_id",
        using: "BTREE",
        fields: [
          { name: "userId" },
        ]
      },
      {
        name: "idx_activities_type_entity",
        using: "BTREE",
        fields: [
          { name: "activityType" },
          { name: "entityId" },
        ]
      },
      {
        name: "idx_activities_action",
        using: "BTREE",
        fields: [
          { name: "action" },
        ]
      },
      {
        name: "idx_activities_created_at",
        using: "BTREE",
        fields: [
          { name: "createdAt" },
        ]
      },
      {
        name: "idx_activities_severity",
        using: "BTREE",
        fields: [
          { name: "severity" },
        ]
      },
      {
        name: "idx_activities_visible",
        using: "BTREE",
        fields: [
          { name: "isVisible" },
        ]
      }
    ]
  });

  Activity.associate = models => {
    Activity.belongsTo(models.User, {
      as: 'User',
      foreignKey: 'userId'
    });
  };

  return Activity;
};
